//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub use super::post::Entity as Post;
pub use super::reservation_changes::Entity as ReservationChanges;
pub use super::reservations::Entity as Reservations;
